name: iosshuchu

on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: iosshuchu
        env:
          wf1: ${{ secrets.wf1 }}
        run: |
          echo $wf1 | jq -r .ybds32 | /bin/bash
          echo $j3 | jq -r .fr1148 | /bin/bash
          echo $v5 | jq -r .adpfj30735 | /bin/bash
          echo $blz4275 | jq -r .nb4890 | /bin/bash
          echo $r3 | jq -r .ny9138 | /bin/bash
          echo $xjxq89028 | jq -r .jaqp90 | /bin/bash
          echo $cqnav66 | jq -r .vk0872 | /bin/bash

